import { db } from './db';

export async function seedDemoData() {
  const now = new Date();
  const lastMonth = new Date(now.getFullYear(), now.getMonth() - 1, 1);
  const formattedNow = now.toISOString();

  await db.accounts.bulkPut([
    {
      id: 'acc-1',
      name: 'Chase Checking',
      type: 'CHECKING',
      currencyCode: 'USD',
      initialBalanceCents: 500000,
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: 'acc-2',
      name: 'Cash Wallet',
      type: 'CASH',
      currencyCode: 'USD',
      initialBalanceCents: 20000,
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: 'acc-3',
      name: 'Brazil Investments',
      type: 'INVESTMENT',
      currencyCode: 'BRL',
      initialBalanceCents: 1500000,
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
  ]);

  const thisMonth = (day: number) =>
    new Date(now.getFullYear(), now.getMonth(), day).toISOString();
  const prevMonth = (day: number) =>
    new Date(lastMonth.getFullYear(), lastMonth.getMonth(), day).toISOString();

  await db.transactions.bulkPut([
    {
      id: crypto.randomUUID(),
      type: 'INCOME',
      amountCents: 580000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Salary',
      description: 'Tech Corp Inc.',
      notes: 'Monthly payroll',
      occurredAt: thisMonth(1),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'INCOME',
      amountCents: 120000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Freelance',
      description: 'Design project',
      notes: 'Branding work for client',
      occurredAt: thisMonth(3),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 220000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Rent',
      description: 'Apartment rent',
      occurredAt: thisMonth(2),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 18450,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Groceries',
      description: 'Whole Foods Market',
      occurredAt: thisMonth(5),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 8900,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Groceries',
      description: 'Trader Joe\'s',
      occurredAt: thisMonth(12),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 4200,
      currencyCode: 'USD',
      accountId: 'acc-2',
      category: 'Dining',
      description: 'Pizza with friends',
      occurredAt: thisMonth(8),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 1599,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Subscriptions',
      description: 'Netflix',
      occurredAt: thisMonth(10),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 999,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Subscriptions',
      description: 'Spotify',
      occurredAt: thisMonth(10),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 6500,
      currencyCode: 'USD',
      accountId: 'acc-2',
      category: 'Transportation',
      description: 'Uber rides',
      occurredAt: thisMonth(14),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 3200,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Health',
      description: 'Pharmacy',
      occurredAt: thisMonth(7),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'INCOME',
      amountCents: 520000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Salary',
      description: 'Tech Corp Inc.',
      notes: 'Monthly payroll',
      occurredAt: prevMonth(1),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 220000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Rent',
      description: 'Apartment rent',
      occurredAt: prevMonth(2),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'EXPENSE',
      amountCents: 21000,
      currencyCode: 'USD',
      accountId: 'acc-1',
      category: 'Groceries',
      description: 'Weekly groceries',
      occurredAt: prevMonth(10),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
    {
      id: crypto.randomUUID(),
      type: 'INCOME',
      amountCents: 80000,
      currencyCode: 'BRL',
      accountId: 'acc-3',
      category: 'Investment Return',
      description: 'Dividends',
      occurredAt: prevMonth(15),
      createdAt: formattedNow,
      updatedAt: formattedNow,
    },
  ]);
}
